### ISSUE TITLE
URIs allowed but unhandled

### ISSUE THREAD

**Issue by jpouellet** [anoadragon453/qubes-mime-types#1]
Use of %U in Exec= in \*.desktop means it's legal for qvm-\* to be passed file:///... (and other URIs) instead of local paths, which it does not handle. See: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

**Comment by anoadragon453** [comment]
Ah, that was copied from qvm-open-in-dvm, I'll remove it.

**Comment by anoadragon453** [comment]
In fact I don't think we even need a .desktop file any more since we ended up patching Nautilus and the .desktop file was just a workaround before doing the patch.

**Comment by anoadragon453** [comment]
Closed in 57598f1.

**Comment by anoadragon453** [comment]
Ok, we still want the Dolphin-related .desktop files as those add the menu items to Dolphin, but we can remove the one relating to Nautilus as that has been patched separately.
