### ISSUE TITLE
Cache untrusted phrase

### ISSUE THREAD

**Issue by jpouellet** [anoadragon453/qubes-mime-types#8]
https://github.com/anoadragon453/qubes-mime-types/blob/0b8b5a85522499462e48e00dc4915246a73ec790/qubesfiletrust/qvm_file_trust.py#L197-L211

No need to re-read the phrase file on each dir check in the same invocation.

Can hoist this to one-time initialization someplace.

**Comment by anoadragon453** [comment]
Good point! Fixed in f690e80.
